from enum import Enum

class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    FAILED = "FAILED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    RECOVERED = "RECOVERED"
    REFUNDED = "REFUNDED"

class FailureCategory(str, Enum):
    TEMPORARY_ISSUER_DECLINE = "TEMPORARY_ISSUER_DECLINE"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    SUSPICIOUS_FRAUD = "SUSPICIOUS_FRAUD"
    UNSUPPORTED_METHOD = "UNSUPPORTED_METHOD"
    EXPIRED_CARD = "EXPIRED_CARD"
    UNKNOWN = "UNKNOWN"

class RecoveryState(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RECOVERY_ELIGIBLE = "RECOVERY_ELIGIBLE"
    RECOVERY_PLANNED = "RECOVERY_PLANNED"
    POLICY_APPROVED = "POLICY_APPROVED"
    ACTION_EXECUTING = "ACTION_EXECUTING"
    AWAITING_PAYMENT_EVENT = "AWAITING_PAYMENT_EVENT"
    RECOVERED = "RECOVERED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"

class InterventionType(str, Enum):
    DELAYED_RETRY = "DELAYED_RETRY"
    ALTERNATIVE_PAYMENT = "ALTERNATIVE_PAYMENT"
    PAYMENT_LINK = "PAYMENT_LINK"
    CUSTOMER_NOTIFICATION = "CUSTOMER_NOTIFICATION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP = "STOP"
    NO_ACTION = "NO_ACTION"

class PolicyResultStatus(str, Enum):
    ALLOWED = "ALLOWED"
    OVERRIDDEN_TO_ESCALATE = "OVERRIDDEN_TO_ESCALATE"
    BLOCKED = "BLOCKED"
    STOPPED = "STOPPED"

class RiskTier(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ActorType(str, Enum):
    SYSTEM_AGENT = "SYSTEM_AGENT"
    POLICY_ENGINE = "POLICY_ENGINE"
    RISK_ENGINE = "RISK_ENGINE"
    MERCHANT_ADMIN = "MERCHANT_ADMIN"
    RAZORPAY_WEBHOOK = "RAZORPAY_WEBHOOK"
