from enum import Enum

class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    FAILED = "FAILED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    RECOVERED = "RECOVERED"
    REFUNDED = "REFUNDED"

class RecoveryType(str, Enum):
    PAYMENT = "PAYMENT"
    CHECKOUT = "CHECKOUT"
    SUBSCRIPTION = "SUBSCRIPTION"
    RECEIVABLE = "RECEIVABLE"
    MANDATE = "MANDATE"
    PROMISE_TO_PAY = "PROMISE_TO_PAY"
    VOICE_RECOVERY = "VOICE_RECOVERY"

class ExecutionMode(str, Enum):
    SIMULATED = "SIMULATED"
    LIVE_TEST_MODE = "LIVE_TEST_MODE"
    EXECUTED = "EXECUTED"
    BLOCKED = "BLOCKED"
    ESCALATED = "ESCALATED"

class FailureCategory(str, Enum):
    TEMPORARY_ISSUER_DECLINE = "TEMPORARY_ISSUER_DECLINE"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    SUSPICIOUS_FRAUD = "SUSPICIOUS_FRAUD"
    UNSUPPORTED_METHOD = "UNSUPPORTED_METHOD"
    EXPIRED_CARD = "EXPIRED_CARD"
    CUSTOMER_DROPOFF = "CUSTOMER_DROPOFF"
    SUBSCRIPTION_RENEWAL_FAILURE = "SUBSCRIPTION_RENEWAL_FAILURE"
    RECEIVABLE_OVERDUE = "RECEIVABLE_OVERDUE"
    MANDATE_CLEARING_ERROR = "MANDATE_CLEARING_ERROR"
    PROMISE_BREACHED = "PROMISE_BREACHED"
    VOICE_OUTREACH_REQUIRED = "VOICE_OUTREACH_REQUIRED"
    UNKNOWN = "UNKNOWN"

class RecoveryState(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RECOVERY_ELIGIBLE = "RECOVERY_ELIGIBLE"
    RECOVERY_PLANNED = "RECOVERY_PLANNED"
    POLICY_APPROVED = "POLICY_APPROVED"
    ACTION_EXECUTING = "ACTION_EXECUTING"
    AWAITING_PAYMENT_EVENT = "AWAITING_PAYMENT_EVENT"
    RECOVERED = "RECOVERED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"

class InterventionType(str, Enum):
    DELAYED_RETRY = "DELAYED_RETRY"
    ALTERNATIVE_PAYMENT = "ALTERNATIVE_PAYMENT"
    PAYMENT_LINK = "PAYMENT_LINK"
    CUSTOMER_NOTIFICATION = "CUSTOMER_NOTIFICATION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP = "STOP"
    NO_ACTION = "NO_ACTION"
    # Expanded Capability Interventions
    CHECKOUT_RECOVERY_LINK = "CHECKOUT_RECOVERY_LINK"
    SUBSCRIPTION_COOLDOWN_RETRY = "SUBSCRIPTION_COOLDOWN_RETRY"
    CARD_UPDATE_REQUEST = "CARD_UPDATE_REQUEST"
    CHASER_NOTIFICATION = "CHASER_NOTIFICATION"
    MANDATE_STEP_SEQUENCE = "MANDATE_STEP_SEQUENCE"
    HINGLISH_VOICE_OUTREACH = "HINGLISH_VOICE_OUTREACH"
    PROMISE_PRE_DUE_REMINDER = "PROMISE_PRE_DUE_REMINDER"
    PROMISE_BREACH_ESCALATE = "PROMISE_BREACH_ESCALATE"

class PolicyResultStatus(str, Enum):
    ALLOWED = "ALLOWED"
    OVERRIDDEN_TO_ESCALATE = "OVERRIDDEN_TO_ESCALATE"
    BLOCKED = "BLOCKED"
    STOPPED = "STOPPED"

class RiskTier(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ActorType(str, Enum):
    SYSTEM_AGENT = "SYSTEM_AGENT"
    POLICY_ENGINE = "POLICY_ENGINE"
    RISK_ENGINE = "RISK_ENGINE"
    MERCHANT_ADMIN = "MERCHANT_ADMIN"
    OPERATIONS_AGENT = "OPERATIONS_AGENT"
    RAZORPAY_WEBHOOK = "RAZORPAY_WEBHOOK"
    VOICE_AGENT = "VOICE_AGENT"
